version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: olanrewaju1992/reverseproxy
  backend_user:
    build:
      context: ../../udagram-c3-restapi-user
    image: olanrewaju1992/udagram-c3-restapi-user
  backend_feed:
    build:
      context: ../../udagram-c3-restapi-feed
    image: olanrewaju1992/udagram-c3-restapi-feed
  frontend:
    build:
      context: ../../udagram-c3-frontend
    image: olanrewaju1992/udagram-c3-frontend
