version: "3"
services:
  reverseproxy:
      image: olanrewaju1992/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - restapi-user
        - restapi-feed
  backend-user:
    image: olanrewaju1992/udagram-c3-restapi-user
    volumes:
      - /usr/bin/aws
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD
      POSTGRESS_DATABASE: $POSTGRESS_DATABASE
      POSTGRESS_HOST: $POSTGRESS_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: olanrewaju1992/udagram-c3-restapi-feed
    volumes:
      - /usr/bin/aws
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD
      POSTGRESS_DATABASE: $POSTGRESS_DATABASE
      POSTGRESS_HOST: $POSTGRESS_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: olanrewaju1992/udagram-c3-frontend
    ports:
      - "8100:80