language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api .
  - docker tag udagram-api olanrewaju1992/udagram-api:latest

after_success:
  - echo "olanrewaju" | docker login -u "olanrewaju1992" --password-stdin
  - docker push olanrewaju1992/udagram-api
